// Single source of truth for the V20 "Our Work" content.
// Sourced verbatim from `TMA _ Where Strategy Meets Bold Storytelling.pdf` —
// deep case-study copy (problem/solution/results) is the agency's own words from
// the deck; short entries are one tight paragraph each that summarises what the
// PDF visually shows for that brand.

const A = "/assets/portfolio";
const V = "/assets/videos"; // production / animation films lifted from the deck

export const PROJECTS = [
  // ============ DEEP CASE STUDIES =========================================
  {
    slug: "foodics-boundless",
    client: "Foodics",
    title: "Boundless 2022 / 2023",
    category: "Event Marketing",
    year: "2022 — 2023",
    tagline: "Launching what's next for F&B",
    thumb: `${A}/foodics-boundless/thumb.jpg`,
    hero: `${A}/foodics-boundless/hero.jpg`,
    video: `${V}/hero1.mp4`,
    gallery: [
      `${A}/foodics-boundless/brand.jpg`,
      `${A}/foodics-boundless/social.jpg`,
      `${A}/foodics-boundless/render.jpg`,
      `${A}/foodics-boundless/tvc.jpg`,
      `${A}/foodics-boundless/social-2.jpg`,
    ],
    services: ["Event Strategy", "Brand Positioning", "Content Production", "Go-to-Market"],
    deep: true,
    intro:
      "We shaped Foodics' brand reputation and positioning from its early $2M funding stage, building a solid strategy and comprehensive brand guidelines that anchored it as the F&B tech leader. We created and executed the flagship Boundless events (2022 & 2023) from scratch, establishing them as premier annual product showcases.",
    problem: [
      "Foodics was evolving from being known mainly as a POS provider into the complete F&B growth platform — offering payments, lending, data and marketplaces.",
      "But the market still largely perceived them as just a POS system.",
      "They needed to educate thousands of restaurant owners and operators about these new tools, and to establish clear market leadership as competition increased in Saudi and beyond.",
    ],
    solution: [
      "Created a flagship annual stage to position Foodics as the authority shaping the future of F&B tech.",
      "Crafted end-to-end event narratives that showed how Foodics solves merchant problems — from payments (Foodics Pay) to financing (Foodics Capital) to scaling via Marketplace.",
      "Designed experiences that educated and excited — live demos, case studies, data insights and launches that made complex products feel essential.",
      "Transformed perception so Foodics was no longer seen just as a POS provider, but as the growth engine for F&B businesses.",
    ],
    results: [
      { metric: "+35.6%", label: "Revenue YoY ($15.4M → $20.8M, 2023→2024)" },
      { metric: "32,000+", label: "Merchants (up from 8,000)" },
      { metric: "35%", label: "Saudi market share" },
      { metric: "$1B", label: "Unicorn valuation reached" },
    ],
  },
  {
    slug: "zid-ripple",
    client: "Zid",
    title: "Ripple 2024 — Total Commerce",
    category: "Product Launch · Event",
    year: "2024",
    tagline: "Launching the Total Commerce era",
    thumb: `${A}/zid-ripple/thumb.jpg`,
    hero: `${A}/zid-ripple/hero.jpg`,
    video: `${V}/Zid%20-%20Strategy.MP4`,
    gallery: [
      `${A}/zid-ripple/brand.jpg`,
      `${A}/zid-ripple/social.jpg`,
      `${A}/zid-ripple/landing.jpg`,
      `${A}/zid-ripple/landing-2.jpg`,
      `${A}/zid-ripple/tvc.jpg`,
    ],
    services: ["Marketing Restructure", "Brand Refresh", "Event Production", "Campaign Execution"],
    deep: true,
    intro:
      "We restructured Zid's marketing department, launched new brand guidelines and a dynamic website, then conceptualised and delivered Ripple 2024 — Zid's first-ever product event — positioning the brand as the leading total commerce platform for merchants. Our work extended to end-to-end campaign execution, from Amazon, Trendyol and Noon integrations to managing all social platforms and high-impact paid materials.",
    problem: [
      "Fragmented systems: merchants struggled to juggle separate tools for e-commerce, social channels and physical outlets.",
      "Scale barriers: logistical inefficiencies and disconnected marketing limited merchant growth.",
      "Perception gap: Zid needed to position itself as the unified, future-ready commerce partner — not just a storefront builder.",
    ],
    solution: [
      "Launched “Total Commerce” as Zid's core product — a seamless ecosystem for e-commerce, social and offline retail operations.",
      "Hosted a flagship event in Diriyah with 1,000+ merchants, industry leaders and government figures — reinforcing Zid's market leadership.",
      "Showcased unified dashboard and logistics so merchants could manage inventory, fulfilment and cross-border operations from one interface.",
      "Revealed AI-powered marketing tools and integrations with TikTok, Amazon, Snapchat and Meta, plus predictive analytics for smarter campaigns.",
    ],
    results: [
      { metric: "200%", label: "Brand growth YoY" },
      { metric: "+30%", label: "Active merchants (12,000+ users)" },
      { metric: "+50%", label: "Basket size & conversion lift" },
      { metric: "+25%", label: "GMV growth YoY" },
    ],
  },

  // ============ SHORT BRAND ENTRIES =======================================
  {
    slug: "sol-brand",
    client: "Sol",
    title: "Brand & Ramadan",
    category: "Social · TVC",
    year: "2024",
    tagline: "Heritage colours, modern logistics",
    thumb: `${A}/sol-brand/thumb.jpg`,
    hero: `${A}/sol-brand/hero.jpg`,
    gallery: [`${A}/sol-brand/tvc.jpg`],
    services: ["Social Media", "Brand Campaigns", "TVC Production"],
    deep: false,
    intro:
      "Sol's orange identity carried across Saudi heritage storytelling, “El-Sebak” pre-Ramadan planning posts and warm, food-forward Ramadan social — turning a delivery brand into a household name with cultural weight.",
  },
  {
    slug: "salasa-2034",
    client: "Salasa",
    title: "FIFA 2034 + National Day",
    category: "Social",
    year: "2024 — 2025",
    tagline: "Reaching its peak in 2025",
    thumb: `${A}/salasa-2034/thumb.jpg`,
    hero: `${A}/salasa-2034/hero.jpg`,
    gallery: [`${A}/salasa-2034/alt.jpg`],
    services: ["Social Media", "Brand Campaigns"],
    deep: false,
    intro:
      "Activated Salasa around two flagship national moments — Saudi National Day with a stadium-delivery hero post, and Saudi Arabia's FIFA World Cup 2034 hosting announcement — then carried that energy into a “25 Shipping Partners” campaign positioning Salasa as the one solution to fulfil every order.",
  },
  {
    slug: "lsc-vision-2034",
    client: "LSC",
    title: "Vision 2034 + WCA",
    category: "Social · Industry",
    year: "2024",
    tagline: "A triumph of vision, ambition and progress",
    thumb: `${A}/lsc-vision-2034/thumb.jpg`,
    hero: `${A}/lsc-vision-2034/hero.jpg`,
    video: `${V}/LSC%20FD%20-%20v4%20(1).mp4`,
    gallery: [`${A}/lsc-vision-2034/alt.jpg`],
    services: ["Social Media", "Industry Storytelling", "Brand Film"],
    deep: false,
    intro:
      "Positioned LSC at the centre of Saudi Arabia's logistics rise — AI-shipping safety explainers, a Vision 2034 hero film, a Ramadan brand moment, and on-the-ground coverage of the WCA Wide Conference where LSC met the world.",
  },
  {
    slug: "invoiceq-identity",
    client: "InvoiceQ",
    title: "Fintech Identity",
    category: "Brand Identity",
    year: "2024",
    tagline: "More practical, consistent and dynamic",
    thumb: `${A}/invoiceq-identity/thumb.jpg`,
    hero: `${A}/invoiceq-identity/hero.jpg`,
    gallery: [],
    services: ["Brand Identity", "Guidelines", "Mobile UI"],
    deep: false,
    intro:
      "Built InvoiceQ a teal-and-navy identity system covering the wordmark, “Q” brand icon, IBM-Plex-style typography, gradient palette and mobile UI showcase — a fintech presence that's both warm and authoritative.",
  },
  {
    slug: "transform-identity",
    client: "Transform",
    title: "Brand System",
    category: "Brand Identity",
    year: "2024",
    tagline: "Bold black, electric yellow",
    thumb: `${A}/transform-identity/thumb.jpg`,
    hero: `${A}/transform-identity/hero.jpg`,
    gallery: [],
    services: ["Brand Identity", "Art Direction", "Photography"],
    deep: false,
    intro:
      "Transform's identity pairs sharp serif logotype work with bold black-and-yellow art direction — storefront signage, mobile UI, custom symbol set and a striking face-paint editorial image that anchors the visual world.",
  },
  {
    slug: "fraed-international",
    client: "Fra'ed International",
    title: "Identity & Apparel",
    category: "Brand Identity",
    year: "2024",
    tagline: "Black, yellow, dot-pattern signature",
    thumb: `${A}/fraed-international/thumb.jpg`,
    hero: `${A}/fraed-international/hero.jpg`,
    gallery: [],
    services: ["Brand Identity", "Packaging", "Apparel"],
    deep: false,
    intro:
      "Fra'ed International got a complete brand system: arabic-and-english logotype, yellow-dot signature pattern carried across notebooks, shopping bags and uniform tees, plus a clean palette and stationery suite ready to roll out everywhere the brand goes.",
  },
  {
    slug: "burger-king-krispier",
    client: "Burger King",
    title: "Get Your Krispier Within 5",
    category: "Campaign",
    year: "2023",
    tagline: "Five-minute drive-thru promise",
    thumb: `${A}/burger-king-krispier/thumb.jpg`,
    hero: `${A}/burger-king-krispier/hero.jpg`,
    gallery: [],
    services: ["Campaign", "Art Direction"],
    deep: false,
    intro:
      "Burger King KSA's “Get your krispier within 5” campaign turned the drive-thru clock into a brand promise — bold red, bold typography, and a Smiley-King double-stack visual that made the wait worth it.",
  },
  {
    slug: "lg-lifes-good",
    client: "LG Saudi",
    title: "Life's Good",
    category: "Brand · Product",
    year: "2023",
    tagline: "Life's Good, brought to Saudi",
    thumb: `${A}/lg-lifes-good/thumb.jpg`,
    hero: `${A}/lg-lifes-good/hero.jpg`,
    gallery: [`${A}/lg-lifes-good/alt.jpg`],
    services: ["Brand Campaigns", "Product Marketing"],
    deep: false,
    intro:
      "LG Saudi launches across air-conditioning and lifestyle product lines — “Life's Good” master brand work, an AC-cooling teaser series, and a free maintenance week campaign localised for the GCC market.",
  },
  {
    slug: "vodafone-global",
    client: "Vodafone",
    title: "Global Brand Films",
    category: "Animation · TVC",
    year: "2023",
    tagline: "Going global",
    thumb: `${A}/vodafone-global/thumb.jpg`,
    hero: `${A}/vodafone-global/hero.jpg`,
    video: `${V}/voda.mp4`,
    gallery: [`${A}/vodafone-global/alt.jpg`],
    services: ["Animation", "Post-Production", "Brand Films"],
    deep: false,
    intro:
      "Cinematic “Global” brand films built on top-down city footage, plus a Vodafone “9” identity short — Vodafone's signature red anchoring a story about scale, speed and connection.",
  },
  {
    slug: "foodics-pay",
    client: "Foodics",
    title: "Pay at Table",
    category: "Landing Page · Product",
    year: "2024",
    tagline: "Zero delay for your customers to pay",
    thumb: `${A}/foodics-pay/thumb.jpg`,
    hero: `${A}/foodics-pay/hero.jpg`,
    gallery: [],
    services: ["Landing Page Design", "Product Marketing"],
    deep: false,
    intro:
      "Foodics Pay-at-Table landing page — a clean restaurant-floor product hero with a single CTA, copy that explains the value in one beat (“Zero delay for your customers to pay”), and a phone showing the in-table checkout flow.",
  },
  {
    slug: "foodics-display",
    client: "Foodics",
    title: "Customer Display Screen",
    category: "Landing Page · Product",
    year: "2024",
    tagline: "Confirm and tap to pay",
    thumb: `${A}/foodics-display/thumb.jpg`,
    hero: `${A}/foodics-display/hero.jpg`,
    gallery: [],
    services: ["Landing Page Design", "Product Marketing"],
    deep: false,
    intro:
      "Launch page for the Foodics 8-inch customer-display screen — sits next to the cashier, shows the order in real time, and lets the customer confirm and tap to pay without ever turning the POS around.",
  },
  {
    slug: "foodics-egypt-ooh",
    client: "Foodics",
    title: "Egypt Launch — OOH",
    category: "OOH · Launch",
    year: "2024",
    tagline: "Cairo, meet Foodics",
    thumb: `${A}/foodics-egypt-ooh/thumb.jpg`,
    hero: `${A}/foodics-egypt-ooh/hero.jpg`,
    gallery: [],
    services: ["OOH", "Go-to-Market", "Campaign"],
    deep: false,
    intro:
      "Foodics' Egypt market entry, executed as a city-wide OOH rollout — bridge billboards over Cairo ring roads, residential street static, and night-time digital sites announcing Foodics to the entire Egyptian F&B trade in one weekend.",
  },

  // ============ PRODUCTION / ANIMATION FILMS (with video) =================
  {
    slug: "rubicon-exotic",
    client: "Rubicon",
    title: "Exotic Juice Drinks",
    category: "TVC · Animation",
    tagline: "Delicious exotic juice drinks",
    thumb: `${V}/posters/rubicon.jpg`,
    hero: `${V}/posters/rubicon.jpg`,
    video: `${V}/media16.mp4`,
    gallery: [],
    services: ["Concept", "CGI / Animation", "Film Production"],
    deep: false,
    intro:
      "A playful product film for Rubicon Exotic — CGI fruit and fizz, skate-park energy and the line “delicious exotic juice drinks” carrying the can from splash to sip.",
  },
  {
    slug: "linc-card",
    client: "LINC",
    title: "Credit Card",
    category: "Product Film",
    tagline: "0% interest at your favourite stores",
    thumb: `${V}/posters/linc.jpg`,
    hero: `${V}/posters/linc.jpg`,
    video: `${V}/media17.mp4`,
    gallery: [],
    services: ["Product Film", "Motion Graphics"],
    deep: false,
    intro:
      "A product film for the LINC credit card — crimson art direction, a gold-card hero, and the offer up front: installments with 0% interest, accepted at your favourite stores.",
  },
  {
    slug: "zaintech-drones",
    client: "ZainTECH",
    title: "Drone Surveying & Mapping",
    category: "Technology Film",
    tagline: "Faster. Precise. Hyperrealistic.",
    thumb: `${V}/posters/zaintech.jpg`,
    hero: `${V}/posters/zaintech.jpg`,
    video: `${V}/Main%20Zainteck%20en%20Final.mp4`,
    gallery: [],
    services: ["Film Production", "3D / VFX", "Brand Storytelling"],
    deep: false,
    intro:
      "A cinematic technology film for ZainTECH's drone surveying and mapping — autonomous drones, CAD and 3D digital-twin tower inspection, time-lapse site capture and ZainTECH's advisory services, framed as a game-changer for the industry.",
  },
  {
    slug: "investcorp-capital",
    client: "Investcorp Capital",
    title: "Strategic Capital",
    category: "Brand Film",
    tagline: "Access to strategic capital",
    thumb: `${V}/posters/investcorp.jpg`,
    hero: `${V}/posters/investcorp.jpg`,
    video: `${V}/hero2.mp4`,
    gallery: [],
    services: ["Brand Film", "Post-Production"],
    deep: false,
    intro:
      "An institutional brand film for Investcorp Capital — top-down global cityscapes, twenty years of excellence, access to strategic capital and an 8% target annual yield, in a restrained navy treatment.",
  },
  {
    slug: "mawani-vision-2030",
    client: "MAWANI",
    title: "Saudi Ports · Vision 2030",
    category: "Corporate Film",
    tagline: "A logistics hub on two vital seas",
    thumb: `${V}/posters/mawani.jpg`,
    hero: `${V}/posters/mawani.jpg`,
    video: `${V}/media8.mp4`,
    gallery: [],
    services: ["Corporate Film", "Post-Production"],
    deep: false,
    intro:
      "A Vision 2030 film for MAWANI, the Saudi Ports Authority — global trade routes, container terminals and Saudi-flag fleets positioning the Kingdom as a logistics hub linking two vital seas.",
  },
  {
    slug: "world-government-summit",
    client: "World Government Summit",
    title: "Next Generation of Minds",
    category: "Brand Film",
    tagline: "To inspire the next generation of minds",
    thumb: `${V}/posters/wgs.jpg`,
    hero: `${V}/posters/wgs.jpg`,
    video: `${V}/media14.mp4`,
    gallery: [],
    services: ["Brand Film", "Post-Production"],
    deep: false,
    intro:
      "A manifesto film for the World Government Summit in Dubai — sweeping city and nature cinematography building to a single promise: to inspire the next generation of minds.",
  },
  {
    slug: "family-development-finance",
    client: "Family Development Centers",
    title: "Financial Awareness",
    category: "Animation · Explainer",
    tagline: "A family life free of debt",
    thumb: `${V}/posters/family-dev.jpg`,
    hero: `${V}/posters/family-dev.jpg`,
    video: `${V}/media15.mp4`,
    gallery: [],
    services: ["2D Animation", "Scriptwriting", "Explainer"],
    deep: false,
    intro:
      "A 2D animated financial-literacy explainer for the Department of Family Development Centers — how families can live debt-free through budgeting, saving and investing, told with friendly characters and a clear, warm system.",
  },
  {
    slug: "sharjah-data-smart-gov",
    client: "Sharjah Data",
    title: "Smart Government",
    category: "Animation · Explainer",
    tagline: "Toward a smarter government",
    thumb: `${V}/posters/sharjah-data.jpg`,
    hero: `${V}/posters/sharjah-data.jpg`,
    video: `${V}/media26.mp4`,
    gallery: [],
    services: ["3D Animation", "Motion Graphics", "Explainer"],
    deep: false,
    intro:
      "A gold-toned animated explainer for Sharjah Data (Bayanat Al-Sharjah) — a smart-government story of connected services, AI and data security, rendered as iconographic 3D motion graphics over a city skyline.",
  },

  // ============ ADDITIONAL BRAND / CAMPAIGN WORK ==========================
  {
    slug: "vanellis",
    client: "Vanelli's",
    title: "Fresh Italian Foods",
    category: "Brand · Social",
    tagline: "New taste of real pasta",
    thumb: `${A}/vanellis/thumb.jpg`,
    hero: `${A}/vanellis/hero.jpg`,
    gallery: [],
    services: ["Brand Campaigns", "Social Media", "Art Direction"],
    deep: false,
    intro:
      "Social and campaign work for Vanelli's, the fresh-Italian-foods brand — Pesto Pasta launches, appetite-led food art direction and Ramadan moments in the brand's signature red.",
  },
  {
    slug: "buffalo-wild-wings",
    client: "Buffalo Wild Wings",
    title: "Now Open — KSA",
    category: "Launch · Social",
    tagline: "Now open",
    thumb: `${A}/buffalo-wild-wings/thumb.jpg`,
    hero: `${A}/buffalo-wild-wings/hero.jpg`,
    gallery: [],
    services: ["Launch Campaign", "Social Media"],
    deep: false,
    intro:
      "Launch creative announcing Buffalo Wild Wings' arrival in the Kingdom — the iconic black-and-yellow buffalo mark front and centre with a bold “Now Open” call.",
  },
  {
    slug: "avis",
    client: "AVIS",
    title: "Car Rental",
    category: "Brand · Social",
    tagline: "Confident, clean key visuals",
    thumb: `${A}/avis/thumb.jpg`,
    hero: `${A}/avis/hero.jpg`,
    gallery: [],
    services: ["Brand Campaigns", "Social Media"],
    deep: false,
    intro:
      "Brand and social work for AVIS in the region — the rental brand's crimson identity carried across clean, confident key-visual layouts.",
  },
  {
    slug: "mixy",
    client: "Mixy",
    title: "Food Brand",
    category: "Brand · Social",
    tagline: "Playful, appetite-led social",
    thumb: `${A}/mixy/thumb.jpg`,
    hero: `${A}/mixy/hero.jpg`,
    gallery: [],
    services: ["Brand Campaigns", "Social Media"],
    deep: false,
    intro:
      "Brand and social creative for Mixy — a playful red food-brand identity and appetite-driven social built for the Saudi market.",
  },
  {
    slug: "tawasol",
    client: "Tawasol",
    title: "Government Platform",
    category: "Identity · Social",
    tagline: "tawasol.gov.jo",
    thumb: `${A}/tawasol/thumb.jpg`,
    hero: `${A}/tawasol/hero.jpg`,
    gallery: [],
    services: ["Identity", "Communications", "Social Media"],
    deep: false,
    intro:
      "Identity and communications for Tawasol, a Jordanian government-services platform — a calm blue system and bilingual social that makes a public service feel approachable.",
  },
  {
    slug: "almarai",
    client: "Almarai",
    title: "Fleet & Trade",
    category: "Brand",
    tagline: "Region's leading food group",
    thumb: `${A}/almarai/thumb.jpg`,
    hero: `${A}/almarai/hero.jpg`,
    gallery: [],
    services: ["Brand", "Trade Communications"],
    deep: false,
    intro:
      "Brand and trade communications for Almarai — fleet livery and B2B storytelling for the region's leading dairy and food group.",
  },
  {
    slug: "electrolux",
    client: "Electrolux",
    title: "Thinking of You",
    category: "Brand · Product",
    tagline: "Thinking of you",
    thumb: `${A}/electrolux/thumb.jpg`,
    hero: `${A}/electrolux/hero.jpg`,
    gallery: [],
    services: ["Product Marketing", "Brand"],
    deep: false,
    intro:
      "Product and brand work for Electrolux — “Thinking of you” lifestyle key visuals and cooktop/appliance launches in a clean, premium European style.",
  },
];

export const PROJECTS_BY_SLUG = Object.fromEntries(
  PROJECTS.map((p) => [p.slug, p])
);
